linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - goerr113
    - gomnd
    - lll
    - wsl
    - interfacer
    - scopelint
    - golint
    - maligned
    - varnamelen
    # Deprecated
    - exhaustivestruct
    - scopelint
    - golint
    - gomoddirectives
    - interfacer
    - maligned
    - varcheck
    - deadcode
    - structcheck
    - nosnakecase
    - ifshort
    - depguard # Replaced by gomodguard
    # Disabled because of generics
    - rowserrcheck
    - sqlclosecheck
    - wastedassign


issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forbidigo
        - paralleltest
        - testpackage

linters-settings:
  gomodguard:
    blocked:
      # List of blocked modules
      modules:
        - github.com/pkg/errors:
            reason: "This package is archived."
